config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

    resources :users, :cargos, :transports, :warehouses, :workflows
      
    get "/login", to: "sessions#new", as: "login"
    get "/logout", to: "sessions#destroy"
    post "/login", to: "sessions#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assistance_type.rb
class AssistanceType < ApplicationRecord
end

app/models/cargo.rb
class Cargo < ApplicationRecord
    belongs_to :user
end

app/models/one.rb
class One < ApplicationRecord
  belongs_to :good
  belongs_to :tansport
  belongs_to :warehouse
end

app/models/transport.rb
class Transport < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  has_many :cargos
  has_many :transports
  has_many :warehouses
  has_many :users

  def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end
  
  def is_authorized?
    current_user == @user  
  end

  validates :name, presence: true
  validates :email, presence: true
  validates_uniqueness_of :email
  validates :email, format: {with: /@/}

end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  belongs_to :user
end

app/models/workflow.rb
class Workflow < ApplicationRecord
  belongs_to :cargo
  belongs_to :tansport
  belongs_to :warehouse
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def set_user
    @user = current_user	
  end
  
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController

  before_action :current_cargo, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    @cargos = Cargo.all
  end

  def new
    @cargo = Cargo.new
  end

  def create
    @cargo = Cargo.new(cargo_params)
    @cargo.user = current_user
    @cargo.save
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @cargo.update_attributes(cargo_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @cargo.destroy
    redirect_to user_path(@user.id)
  end

  private

  def cargo_params
    params.require(:cargo).permit(:goods, :state, :city, :quantity, :weight, :size, :address, :funding, :shipping)
  end

  def current_cargo
    @cargo = Cargo.find_by_id(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:notice] = "Succesfully logged in."
      redirect_to root_path
    else
      flash[:error] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice] = "Succesfully logged out."
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController

  before_action :current_transport, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    @transports = Transport.all
  end

  def new
    @transport = Transport.new
  end

  def create
    @transport = Transport.new(transport_params)
    @transport.user = current_user
    @transport.save
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @transport.update_attributes(transport_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @transport.destroy
    redirect_to user_path(@user.id)
  end

  private

  def transport_params
    params.require(:transport).permit(:role, :range, :capacity, :name, :avaliability, :funding, :hub)
  end

  def current_transport
    @transport = Transport.find_by_id(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in?, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update]

  def index
  end

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to root_path
    else
      flash[:error] = "Email has already been taken"
      redirect_to 'new_user_path'
    end
  end

  def show
    @user = User.find_by_id(params[:id])
    @cargos = @user.cargos
    @transports = @user.transports
    @warehouses = @user.warehouses
  end

  def edit
  end

  def update
    current_params = params.require(:user).permit(:name, :email, :role)
    @user.update_attributes(current_params)
    redirect_to user_path
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :role)
  end

end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController

  before_action :current_warehouse, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    @warehouses = Warehouse.all
  end

  def new
    @warehouse = Warehouse.new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)
    @warehouse.user = current_user
    @warehouse.save
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @warehouse.update_attributes(warehouse_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @warehouse.destroy
    redirect_to user_path(@user.id)
  end

  private

  def warehouse_params
    params.require(:warehouse).permit(:capacity, :avaliability, :funding, :location)
  end

  def current_warehouse
    @warehouse = Warehouse.find_by_id(params[:id])
  end
end

app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :current_workflow, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create, :show, :update, :destroy]

  def index
    @workflows = Workflow.all
  end

  def new
    @workflow = Workflow.new
  end

  def create
    @workflow = Workflow.new(workflow_params)
    @workflow.user = current_user
    @workflow.save
    redirect_to root_path
  end

  def show
  end

  def edit
  end

  def update
    @workflow.update_attributes(workflow_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @workflow.destroy
    redirect_to user_path(@user.id)
  end

  private

  def workflow_params
    params.require(:workflow).permit(:one, :two, :three, :four, :five, :six, :seven, :eight, :nine, :ten, :elen, :twelve, :thirteeen, :fourteen, :fifteen, :step)
  end

  def current_workflow
    @workflow = Workflow.find_by_id(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assistance_types_helper.rb
module AssistanceTypesHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    if current_user == nil
      redirect_to new_session_path 
    end
  end

  def logged_out?
    if current_user != nil
      redirect_to user_path(current_user)
    end
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def authorized?(user)
    current_user == user
  end
  
end

app/helpers/transports_helper.rb
module TransportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/helpers/workflows_helper.rb
module WorkflowsHelper

  def step_generator
    p @step
  end

end

app/views/cargos/index.html.erb
<div class="container">
  <h2>Donated Cargo</h2>
</div>

<div class="info container">
  <div class="row">
    <% @cargos.each do |d| %>
        <div class="col-md-4">
        <h3>Item: <%= d.goods %></h3>
        <p>Address: <%= d.address %></p>
        <p>City: <%= d.city %></p>
        <p>State: <%= d.state %></p>
        <p>Quantity: <%= d.quantity %></p>
        <p>Weight: <%= d.weight %></p>
        <p>Size: <%= d.size %></p>
        <p>Needs Shiping: <%= d.shipping %></p>
        <p>Needs Funding: <%= d.funding %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/cargos/new.html.erb
<div class="container">
  <%= form_for @cargo, url: {action: "create"} do |f| %>
    <fieldset>
      <h1 class="text-center">Cargo or Goods</h1>

      <div class="form-group row">
        <div class="col-md-2">
          <p>Description of item:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :goods, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>Address:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :address, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>City:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :city, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>State:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :state, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>Quantiy:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :quantity, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>Weight:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :weight, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>Size:</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :size, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>If it requires funding, how much?</p>
        </div>
        <div class="col-md-10">
          <%= f.text_field :funding, required: true, class: "form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-2">
          <p>Does this require shipping?</p>
        </div>
        <div class="col-md-10">
          <%= f.select :shipping, [["Yes", "Yes"], ["No", "No"]], class: "form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.submit "Submit", class: "btn btn-success" %>
      </div>

    </fieldset>
  <% end %>
</div>

app/views/transports/index.html.erb
<div class="container">
  <h2>Avaliable Transport</h2>
</div>

<div class="info container">
  <div class="row">
    <% @transports.each do |d| %>
      <div class="col-md-4">
        <h5>Type: <%= d.role %></h5>
        <p>Kind: <%= d.name %></p>
        <p>Location: <%= d.hub %></p>
        <p>Range: <%= d.range %></p>
        <p>Capacity: <%= d.capacity %></p>
        <p>Avaliability: <%= d.avaliability %></p>
        <p>Funding Required: <%= d.funding %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/transports/new.html.erb
      <%= form_for :transport, url: transports_path do |f| %>
        <fieldset>
          <h1 class="text-center">Transport Form</h1>

          <div class="form-group">
            <label class="col-md-4 control-label" for="role">Air or land transport?</label>
            <div class="col-md-8">
              <%= f.select :role, [["Air", "Air"], ["Land", "Land"], ["Ocean", "Ocean"]], class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="name">What type of vehicle?</label>
            <div class="col-md-8">
              <%= f.text_field :name, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="hub">Main hub/ point of origin</label>
            <div class="col-md-8">
              <%= f.text_field :hub, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="range">Range</label>
            <div class="col-md-8">
              <%= f.text_field :range, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="capacity">Capacity</label>
            <div class="col-md-8">
              <%= f.text_field :capacity, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="avaliabilty">Avaliability</label>
            <div class="col-md-8">
              <%= f.text_field :avaliability, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="avaliabilty">Price</label>
            <div class="col-md-8">
              <%= f.text_field :funding, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Submit", class: "btn btn-success" %>
            </div>
          </div>
          
        </fieldset>
      <% end %>

app/views/users/edit.html.erb
<div class="page">
 
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for @user, url: {action: "update"} do |f| %>
          <fieldset>
            <h1 class="text-center">Edit Profile</h1>

            <div class="form-group">
              <label class="col-md-4 control-label" for="name">Name</label>
              <div class="col-md-8">
                <%= f.text_field :name, required: true, class: "form-control" %><br>
              </div>
            </div>

            <div class="form-group">
              <label class="col-md-4 control-label" for="email">Email</label>
              <div class="col-md-8">
                <%= f.text_field :email, required: true, class: "form-control" %><br>
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-12">
                <%= f.submit "Save", class: "btn btn-success" %>
              </div>
            </div>
            
          </fieldset>
        <% end %>
      </div>
    </div>

</div>

app/views/users/index.html.erb
<div class="container">
  <h1>SUPPORT PUERTO RICO'S RECOVERY!</h1> 
</div>

<div class="container">
  <h2>Create a new Workflow</h2>
  <% if current_user.role == "Cordinator" %>
    <%= link_to "Create New Workflow", new_workflow_path %>
  <% end %>
</div>

<div class="container">
  <h2>HOW CAN YOU HELP?</h2>
  <% if current_user %>
    <li><%= link_to "Volunteer",  root_path %></li>
    <li><%= link_to "Donate Goods", new_cargo_path %></li>
    <li><%= link_to "Donate Money", root_path %></li>
    <li><%= link_to "Provide Transport", new_transport_path %></li>
    <li><%= link_to "Request/Provide Medivac", root_path %></li>
    <li><%= link_to "Warehouse Goods", new_warehouse_path %></li>
  <% else %>
    <li>Volunteer</li>
    <li>Donate Goods</li>
    <li>Donate Money</li>
    <li>Provide Air Transport</li>
    <li>Provide Land Transport</li>
    <li>Request/Provide Medivac</li>
    <li>Warehouse Goods</li>
    <br>
    <p>To provide services you must please Log In or Sign Up!</p>
    <p>Thanks!</p>

  <% end %>
</div>

<div class="container">
  <h4>Current Needs</h4>
  <ul>
    <li><%= link_to "Donated Goods", cargos_path %></li>
    <li><%= link_to "Projects that need Money", root_path %></li>
    <li><%= link_to "Requested Transport", transports_path %></li>
    <li><%= link_to "Requested Warehouse", warehouses_path %></li>
  </ul>
</div>

app/views/users/new.html.erb
<div class="page">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= form_for :user, url: users_path do |f| %>
        <fieldset>
          <h1 class="text-center">Sign Up!</h1>

          <div class="form-group">
            <label class="col-md-4 control-label" for="name">Name</label>
            <div class="col-md-8">
              <%= f.text_field :name, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="email">Email</label>
            <div class="col-md-8">
              <%= f.text_field :email, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password">Password</label>
            <div class="col-md-8">
              <%= f.password_field :password, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="password_confirmation">Confirm Password</label>
            <div class="col-md-8">
              <%= f.password_field :password_confirmation, required: true, class: "form-control" %><br>
            </div>
          </div>

          <div class="form-group">
            <label class="col-md-4 control-label" for="role">What is your Role?</label>
            <div class="col-md-8">
              <%= f.select :role, [["Node", "Node"], ["Cordinator", "Cordinator"]], class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-md-12">
              <%= f.submit "Sign up", class: "btn btn-success" %>
            </div>
          </div>
          
        </fieldset>
      <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container"> 
  <h1>Profile</h1>
  <h4><%= @user.name %></h4>
</div>

<div class="container">
  <% if @user.role == "Cordinator" %>
    <%= link_to "Create New Workflow", new_workflow_path %>
  <% end %>
</div>

<div class="info container">

  <% if @cargos.length > 0 %>
    <h4 class="info-title">Goods You've Donated</h4>
    <div class="row">
      <% @cargos.each do |d| %>
        <div class="col-md-4">
          <p>Item: <%= d.goods %></p>
          <p>Adress: <%= d.address %></p>
          <p>City: <%= d.city %></p>
          <p>State: <%= d.state %></p>
          <p>Quantity: <%= d.quantity %></p>
          <p>Weight: <%= d.weight %></p>
          <p>Size: <%= d.size %></p>
          <p>Needs Shiping: <%= d.shipping %></p>
          <p>Needs Funding: <%= d.funding %></p>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @transports.length > 0 %>
    <h4 class="info-title">Transport You've Provided</h4>
    <div class="row">
      <% @transports.each do |d| %>
        <div class="col-md-4">
          <h5>Type: <%= d.role %></h5>
          <p>Kind: <%= d.name %></p>
          <p>Location: <%= d.hub %></p>
          <p>Range: <%= d.range %></p>
          <p>Capacity: <%= d.capacity %></p>
          <p>Avaliability: <%= d.avaliability %></p>
          <p>Funding Required: <%= d.funding %></p>
        </div>
      <% end %>
    </div>
  <% end %>

  <% if @warehouses.length > 0 %>
    <h4 class="info-title">Warehouse Space You've Provided</h4>
    <div class="row">
      <% @warehouses.each do |d| %>
        <div class="col-md-4">
          <h5>Location: <%= d.location %></h5>
          <p>Capacity: <%= d.capacity %></p>
          <p>Avaliability: <%= d.avaliability %></p>
          <p>Funding Required: <%= d.funding %></p>
        </div>
      <% end %>
    </div>
  <% end %>
  
</div>

app/views/workflows/new.html.erb
<div class="container">
  <h1>New Workflow</h1>

    <%= form_for :workflow, url: workflows_path do |f| %>

      <div class="form-group">
        <label class="col-md-4 control-label" for="location">How Many Steps?</label>
        <div class="col-md-8">
          <%= f.text_field :step, required: true, class: "form-control" %><br>
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-12">
          <%= f.submit "Submit", class: "btn btn-success" %>
        </div>
      </div>

    <% end %>
</div>